# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - CS519Project
env:
  AZURE_WEBAPP_NAME: 'CS519Project'
  WEBAPP_PACKAGE_PATH: 'Node/WEB'
  FRONTEND_PACKAGE_PATH: 'Node/WEB/frontend'
  NODE_VERSION: '20.x'

on:
  push:
    branches:
      - main
    paths:
    - 'Node/WEB/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: './Node/WEB/package.json'
        
      - name: npm install, build, and test
        working-directory: ./Node/WEB
        run: |
          npm install

      - name: npm install react frontend
        working-directory: ./Node/WEB/frontend
        run: |
          npm install
          npm run build
          rm -r public
          rm -r node_modules
          rm -r src

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_834E07B2839D499585A96E8625FCFD11 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AFDF469F40A7476ABA0D14AACCA63C42 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2EABF0556694475397F562067B6DE3D9 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          package: ${{ env.WEBAPP_PACKAGE_PATH }}
          